version: '3'

services:

  nodejs:
    image: node:16.14.0-alpine3.15
    working_dir: /opt/project_root
    volumes:
      - ./:/opt/project_root
    tty: true
    entrypoint: /bin/sh
    command: >
      -c "
      apk add git;
      /bin/sh
      "

  web-proxy:
    image: httpd:2.4.52
    volumes:
      - ./:/var/www/html
      - ./docker_config/web/web_proxy.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker_config/web/ssl/ssl.crt:${SSLCertificateFile}
      - ./docker_config/web/ssl/ssl.key:${SSLCertificateKeyFile}
    ports:
      - "${WEB_IP}:443:443"
    tty: true
    env_file:
      - ./.env
